### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by francis-mwas** [BuildForSDG/team-132-backend#46]
![bp](https://user-images.githubusercontent.com/43579267/84125999-049c3480-aa46-11ea-8e3f-de09d181c344.png)
Please fix the above error.

**Comment by cliffgor** [comment]
@francis-mwas this is what I was getting when I try to run the application

**Comment by obsessedyouth** [comment]
Sorry this was my fault. When I refactored the req, res into the controller, I forgot the body variable no longer existed.
